import { build } from 'npm:vite@^8.1.5';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../..', import.meta.url));

export async function buildCollector(): Promise<void> {
  await build({
    root,
    logLevel: 'warn',
    build: {
      lib: {
        entry: fileURLToPath(new URL('./collector.entry.ts', import.meta.url)),
        name: '__mbdCollectorBundle',
        formats: ['iife'],
        fileName: () => 'collector.iife.js',
      },
      outDir: fileURLToPath(new URL('../../dist', import.meta.url)),
      emptyOutDir: false,
      minify: false,
    },
  });

  // Emit the IIFE as a TS string module. Under `deno desktop`, import.meta.url
  // resolves into a temp compile dir, so the bundle can't be read by relative
  // path at runtime (see docs/runtime-recipe.md). Embedding it as a string that
  // main.ts imports is the reliable path.
  const iife = await Deno.readTextFile(fileURLToPath(new URL('../../dist/collector.iife.js', import.meta.url)));
  const generated = `// AUTO-GENERATED by build-collector.ts — do not edit.\nexport const COLLECTOR_IIFE = ${JSON.stringify(iife)};\n`;
  await Deno.writeTextFile(fileURLToPath(new URL('./collector.generated.ts', import.meta.url)), generated);
}

// Bundle the backend's @mbd/core value-imports into a self-contained ESM the
// desktop backend can import by relative path (deno desktop can't resolve bare
// @mbd/core source imports — see docs/runtime-recipe.md).
export async function buildCoreBundle(): Promise<void> {
  await build({
    root,
    logLevel: 'warn',
    build: {
      lib: {
        entry: fileURLToPath(new URL('../core-bundle/core-entry.ts', import.meta.url)),
        formats: ['es'],
        fileName: () => 'download-name.gen.js',
      },
      outDir: fileURLToPath(new URL('../core-bundle', import.meta.url)),
      emptyOutDir: false,
      minify: false,
      rollupOptions: { external: [] },
    },
  });

  // Vite/Rollup emit plain JS with no type info. Prepend a `@ts-self-types`
  // directive so Deno associates the hand-written download-name.gen.d.ts with
  // this generated file for every importer, without each import site needing
  // its own `@ts-types` comment.
  const genPath = fileURLToPath(new URL('../core-bundle/download-name.gen.js', import.meta.url));
  const bundled = await Deno.readTextFile(genPath);
  await Deno.writeTextFile(genPath, `// @ts-self-types="./download-name.gen.d.ts"\n${bundled}`);
}

if (import.meta.main) {
  await buildCollector();
  await buildCoreBundle();
  console.log('built collector IIFE (+ generated.ts) and core-bundle/download-name.gen.js');
}
