import { build } from 'npm:vite@^8.1.5';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../..', import.meta.url));

/**
 * Bundles `deepscan.entry.ts` into a self-contained IIFE and embeds it as a TS
 * string module, mirroring `buildCollector` in `../build/collector.ts` — same
 * rationale: under `deno desktop`, import.meta.url resolves into a temp compile
 * dir, so the bundle can't be read by relative path at runtime (see
 * docs/runtime-recipe.md). Kept in a sibling module (not `../build/`) so this
 * build script can be authored/edited independently of that directory.
 */
export async function buildDeepScan(): Promise<void> {
  await build({
    root,
    logLevel: 'warn',
    build: {
      lib: {
        entry: fileURLToPath(new URL('./deepscan.entry.ts', import.meta.url)),
        name: '__mbdDeepScanBundle',
        formats: ['iife'],
        fileName: () => 'deepscan.iife.js',
      },
      outDir: fileURLToPath(new URL('../../dist', import.meta.url)),
      emptyOutDir: false,
      minify: false,
    },
  });

  const iife = await Deno.readTextFile(fileURLToPath(new URL('../../dist/deepscan.iife.js', import.meta.url)));
  const generated = `// AUTO-GENERATED by deepscan.build.ts — do not edit.\nexport const DEEPSCAN_IIFE = ${JSON.stringify(iife)};\n`;
  await Deno.writeTextFile(fileURLToPath(new URL('../generated/deepscan-iife.ts', import.meta.url)), generated);
}

if (import.meta.main) {
  await buildDeepScan();
  console.log('built deep-scan IIFE (+ generated.ts)');
}
